import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Use",
  description: "Lectern Terms of Use — the rules governing your use of our AI-powered study platform.",
};

export default function TermsPage() {
  return (
    <>
      <h1>Terms of Use</h1>
      <p className="!text-slate-400 !text-xs">Last updated: March 20, 2026</p>

      <p>
        These Terms of Use (&quot;Terms&quot;) govern your access to and use of the Lectern platform
        (&quot;Service&quot;), operated by Lectern (&quot;we&quot;, &quot;us&quot;, or &quot;our&quot;). By creating
        an account or using the Service, you agree to be bound by these Terms. If you do not agree,
        do not use the Service.
      </p>

      <h2>1. Account Registration</h2>
      <p>
        To use Lectern, you must create an account by providing your full name and email address, or
        by signing in with Google. You are responsible for maintaining the confidentiality of your
        account credentials and for all activity that occurs under your account. You must be at least
        16 years of age to use this Service.
      </p>
      <p>
        You agree to provide accurate, current, and complete information during registration and to
        update such information to keep it accurate. We reserve the right to suspend or terminate
        accounts that contain false or misleading information.
      </p>

      <h2>2. Description of Service</h2>
      <p>
        Lectern is an AI-powered study platform that allows users to access AI-generated lecture
        notes, practice questions, and an AI chat tutor based on course materials uploaded by
        instructors or administrators. The Service includes three primary study modes: Learn
        (lecture slides), Practice (quizzes and exam questions), and Chat (AI tutor).
      </p>

      <h2>3. AI-Generated Content</h2>
      <p>
        The lecture notes, practice questions, model answers, and chat responses provided through
        Lectern are generated by artificial intelligence. While we strive for accuracy and
        pedagogical quality, AI-generated content may contain errors, omissions, or inaccuracies.
      </p>
      <p>
        You acknowledge and agree that:
      </p>
      <ul>
        <li>AI-generated content is provided as a study aid, not as a substitute for official course materials, instructor guidance, or professional advice.</li>
        <li>You should verify important information with your course instructors and official materials.</li>
        <li>We do not guarantee that studying with Lectern will result in any particular academic outcome.</li>
        <li>AI-generated content may not reflect the most current developments in a given field.</li>
      </ul>

      <h2>4. Acceptable Use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Use the Service to violate any applicable law or regulation.</li>
        <li>Upload, share, or distribute content that infringes on the intellectual property rights of others.</li>
        <li>Submit AI-generated content from Lectern as your own original work in academic assessments, unless expressly permitted by your institution.</li>
        <li>Attempt to reverse-engineer, scrape, or extract the AI models or underlying technology.</li>
        <li>Use automated tools, bots, or scripts to access the Service beyond normal usage.</li>
        <li>Harass, abuse, or send harmful content through the chat feature.</li>
        <li>Share your account credentials or allow others to access your account.</li>
      </ul>

      <h2>5. Intellectual Property</h2>
      <p>
        The Lectern platform, including its design, features, and underlying technology, is owned by
        us and protected by intellectual property laws. You retain ownership of any materials you
        upload to the platform. By uploading materials, you grant us a limited, non-exclusive license
        to process and analyze those materials solely for the purpose of generating study aids for
        authorized users of the relevant course.
      </p>
      <p>
        AI-generated study aids produced by the Service are provided for your personal educational
        use. You may not redistribute, sell, or commercially exploit AI-generated content without
        our prior written consent.
      </p>

      <h2>6. Payments and Message Packs</h2>
      <p>
        Lectern offers a free tier of AI chat messages per course enrollment. Additional chat
        messages may be purchased through message packs at prices displayed on the platform.
        Payments are processed securely by Paystack, our third-party payment provider.
      </p>
      <p>
        All purchases are final and non-refundable, except where required by applicable law.
        Message packs do not expire but are tied to a specific course enrollment. We reserve
        the right to change pricing at any time, though changes will not affect previously
        purchased packs.
      </p>

      <h2>7. Privacy</h2>
      <p>
        Your use of the Service is also governed by our{" "}
        <a href="/privacy">Privacy Policy</a>, which describes how we collect, use, and protect
        your personal information. By using the Service, you consent to the practices described
        in our Privacy Policy.
      </p>

      <h2>8. Availability and Modifications</h2>
      <p>
        We strive to keep Lectern available at all times, but we do not guarantee uninterrupted
        access. The Service may be temporarily unavailable for maintenance, updates, or due to
        circumstances beyond our control. We reserve the right to modify, suspend, or discontinue
        any part of the Service at any time, with or without notice.
      </p>

      <h2>9. Termination</h2>
      <p>
        You may delete your account at any time by contacting us. We may suspend or terminate
        your account if you violate these Terms, engage in fraudulent activity, or for any other
        reason at our discretion. Upon termination, your right to use the Service ceases
        immediately. We may retain certain data as required by law or for legitimate business
        purposes.
      </p>

      <h2>10. Limitation of Liability</h2>
      <p>
        To the fullest extent permitted by law, Lectern and its officers, directors, employees,
        and agents shall not be liable for any indirect, incidental, special, consequential, or
        punitive damages arising from your use of or inability to use the Service. Our total
        liability for any claim arising from these Terms shall not exceed the amount you paid us
        in the twelve months preceding the claim.
      </p>
      <p>
        The Service is provided &quot;as is&quot; and &quot;as available&quot; without warranties of any kind,
        whether express or implied, including but not limited to warranties of merchantability,
        fitness for a particular purpose, or non-infringement.
      </p>

      <h2>11. Indemnification</h2>
      <p>
        You agree to indemnify and hold harmless Lectern from any claims, damages, losses, or
        expenses (including reasonable legal fees) arising from your use of the Service, your
        violation of these Terms, or your infringement of any third-party rights.
      </p>

      <h2>12. Changes to These Terms</h2>
      <p>
        We may update these Terms from time to time. We will notify you of material changes by
        posting the updated Terms on this page and updating the &quot;Last updated&quot; date. Your
        continued use of the Service after changes are posted constitutes your acceptance of the
        revised Terms.
      </p>

      <h2>13. Governing Law</h2>
      <p>
        These Terms shall be governed by and construed in accordance with the laws of the Federal
        Republic of Nigeria, without regard to conflict of law principles. Any disputes arising
        under these Terms shall be resolved in the courts of Lagos, Nigeria.
      </p>

      <h2>14. Contact</h2>
      <p>
        If you have questions about these Terms, please contact us at{" "}
        <a href="mailto:legal@lectern.academy">legal@lectern.academy</a>.
      </p>
    </>
  );
}
